const yaml = require('js-yaml');
const fs = require('fs');

module.exports = {
  read: read,
  write: write,
  writeLockfile: writeLockfile
};

function read(filename, cb) {
  fs.readFile(filename, 'utf8', (err, data) => {
    if (err) return cb(err, null);
    try {
      var obj = yaml.safeLoad(data);
      cb(null, obj);
    } catch (err) {
      cb(err, null);
    }
  });
}

function writeLockfile(filename, data, cb) {
  var preamble = [];
  preamble.push(
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
  );
  preamble.push('\n');
  preamble.push('# newwork lockfile v1');
  preamble.push('\n\n');
  preamble = preamble.join('');
  write(filename, data, { preamble: preamble }, cb);
}

function write(filename, data, opts, cb) {
  var cb = cb || opts;
  if (typeof opts === 'function' || !opts) opts = {};

  var preamble = opts.preamble || '';

  try {
    var text = preamble + yaml.safeDump(data);
    fs.writeFile(filename, text, 'utf8', cb);
  } catch (err) {
    cb(err);
  }
}
